jpy001/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('jpy001.views',
    # Examples:
    # url(r'^$', 'jpy001.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'index', name='index'),
    url(r'^skin_config/$', 'skin_config', name='skin_config'),
    url(r'^login/$', 'Login', name='login'),
    url(r'^logout/$', 'Logout', name='logout'),    
    url(r'^jpyasset/', include('jpyasset.urls')),
    url(r'^jpyuser/', include('jpyuser.urls')),
    url(r'^jpydispose/', include('jpydispose.urls')),
)

jpyasset/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from jpyasset.views import *

urlpatterns = patterns('',
    url(r'^host/list/$', host_list, name='host_list'),
    url(r'^host/add/$', host_add, name='host_add'),
    url(r'^host/edit/$', host_edit, name='host_edit'),
    url(r'^host/del/$', host_del, name='host_del'),
    url(r'^host/edit/chg/name/$', host_edit_chg_name, name='host_edit_chg_name'),
    url(r'^host/detail/$', host_detail, name='host_detail'),
    url(r'^host/cloud/list/$', host_cloud_list, name='host_cloud_list'),
    url(r'^host/cloud/update/$', host_cloud_update, name='host_cloud_update'),
    url(r'^net/ip/add/$', net_ip_add, name='net_ip_add'),
    url(r'^net/ip/del/$', net_ip_del, name='net_ip_del'),
    url(r'^net/ip/edit/$', net_ip_edit, name='net_ip_edit'),
    url(r'^net/ip/list/$', net_ip_list, name='net_ip_list'),
    url(r'^net/resource/add/$', net_resource_add, name='net_resource_add'),
    url(r'^net/resource/del/$', net_resource_del, name='net_resource_del'),
    url(r'^net/resource/edit/$', net_resource_edit, name='net_resource_edit'),
    url(r'^net/resource/list/$', net_resource_list, name='net_resource_list'),
    url(r'^net/realm/add/$', net_realm_add, name='net_realm_add'),
    url(r'^net/realm/del/$', net_realm_del, name='net_realm_del'),
    url(r'^net/realm/edit/$', net_realm_edit, name='net_realm_edit'),
    url(r'^net/realm/list/$', net_realm_list, name='net_realm_list'),
    url(r'^storager/cnd/add/$', storager_cnd_add, name='storager_cnd_add'),
    url(r'^storager/cnd/del/$', storager_cnd_del, name='storager_cnd_del'),
    url(r'^storager/cnd/edit/$', storager_cnd_edit, name='storager_cnd_edit'),
    url(r'^storager/cnd/list/$', storager_cnd_list, name='storager_cnd_list'),
    url(r'^storager/cold/add/$', storager_cold_add, name='storager_cold_add'),
    url(r'^storager/cold/del/$', storager_cold_del, name='storager_cold_del'),
    url(r'^storager/cold/edit/$', storager_cold_edit, name='storager_cold_edit'),
    url(r'^storager/cold/list/$', storager_cold_list, name='storager_cold_list'),
    url(r'^idc/add/$', idc_add, name='idc_add'),
    url(r'^idc/del/$', idc_del, name='idc_del'),
    url(r'^idc/edit/$', idc_edit, name='idc_edit'),
    url(r'^idc/list/$', idc_list, name='idc_list'),
    url(r'^itemmg/item/add/$', item_add, name='item_add'),
    url(r'^itemmg/item/del/$', item_del, name='item_del'),
    url(r'^itemmg/item/edit/$', item_edit, name='item_edit'),
    url(r'^itemmg/item/list/$', item_list, name='item_list'),
    url(r'^itemmg/area/add/$', area_add, name='area_add'),
    url(r'^itemmg/area/del/$', area_del, name='area_del'),
    url(r'^itemmg/area/edit/$', area_edit, name='area_edit'),
    url(r'^itemmg/area/list/$', area_list, name='area_list'),
    url(r'^itemmg/funct/add/$', funct_add, name='funct_add'),
    url(r'^itemmg/funct/del/$', funct_del, name='funct_del'),
    url(r'^itemmg/funct/edit/$', funct_edit, name='funct_edit'),
    url(r'^itemmg/funct/list/$', funct_list, name='funct_list'),
    url(r'^vtmg/osname/add/$', osname_add, name='osname_add'),
    url(r'^vtmg/osname/del/$', osname_del, name='osname_del'),
    url(r'^vtmg/osname/edit/$', osname_edit, name='osname_edit'),
    url(r'^vtmg/osname/list/$', osname_list, name='osname_list'),
    url(r'^vtmg/appvl/add/$', appvl_add, name='appvl_add'),
    url(r'^vtmg/appvl/del/$', appvl_del, name='appvl_del'),
    url(r'^vtmg/appvl/edit/$', appvl_edit, name='appvl_edit'),
    url(r'^vtmg/appvl/list/$', appvl_list, name='appvl_list'),
    url(r'^vtmg/filevl/add/$', filevl_add, name='filevl_add'),
    url(r'^vtmg/filevl/del/$', filevl_del, name='filevl_del'),
    url(r'^vtmg/filevl/edit/$', filevl_edit, name='filevl_edit'),
    url(r'^vtmg/filevl/list/$', filevl_list, name='filevl_list'),    
    url(r'^vtmg/confvl/add/$', confvl_add, name='confvl_add'),
    url(r'^vtmg/confvl/del/$', confvl_del, name='confvl_del'),
    url(r'^vtmg/confvl/edit/$', confvl_edit, name='confvl_edit'),
    url(r'^vtmg/confvl/list/$', confvl_list, name='confvl_list'),
    url(r'^vtmg/vervl/add/$', vervl_add, name='vervl_add'),
    url(r'^vtmg/vervl/del/$', vervl_del, name='vervl_del'),
    url(r'^vtmg/vervl/edit/$', vervl_edit, name='vervl_edit'),
    url(r'^vtmg/vervl/list/$', vervl_list, name='vervl_list'),
    url(r'^vtmg/conftaskname/add/$', conftaskname_add, name='conftaskname_add'),
    url(r'^vtmg/conftaskname/del/$', conftaskname_del, name='conftaskname_del'),
    url(r'^vtmg/conftaskname/edit/$', conftaskname_edit, name='conftaskname_edit'),
    url(r'^vtmg/conftaskname/list/$', conftaskname_list, name='conftaskname_list'),
    url(r'^vtmg/conftaskset/add/$', conftaskset_add, name='conftaskset_add'),
    url(r'^vtmg/conftaskset/del/$', conftaskset_del, name='conftaskset_del'),
    url(r'^vtmg/conftaskset/edit/$', conftaskset_edit, name='conftaskset_edit'),
    url(r'^vtmg/conftaskset/list/$', conftaskset_list, name='conftaskset_list'),        
    url(r'^vtmg/planvl/add/$', planvl_add, name='planvl_add'),
    url(r'^vtmg/planvl/del/$', planvl_del, name='planvl_del'),
    url(r'^vtmg/planvl/edit/$', planvl_edit, name='planvl_edit'),
    url(r'^vtmg/planvl/list/$', planvl_list, name='planvl_list'),
)

jpyasset/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from jpy001.settings import MEDIA_ROOT

IDC_TYPE = (
    (1, u"云服务"),
    (2, u"物理服务")
    )

class IDC(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'机房名称')
    idcmark = models.CharField(max_length=16, unique=True, verbose_name=u'机房代号')
    linkman = models.CharField(max_length=16, blank=True, null=True, default='', verbose_name=u'联系人')
    phone = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'联系电话')
    cloudid = models.CharField(max_length=255, blank=True, null=True, default='', verbose_name=u'云SecretId')
    cloudkey = models.CharField(max_length=255, blank=True, null=True, default='', verbose_name=u'云SecretKey')
    cloudregid = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'云所属区域')
    idc_type = models.IntegerField(choices=IDC_TYPE, blank=True, null=True, verbose_name=u"区域类型")    
    date_added = models.DateTimeField(auto_now=True)
    operator = models.CharField(max_length=32, blank=True, default='', null=True, verbose_name=u"运营商")
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name


class Items(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'项目名称')
    itemmark = models.CharField(max_length=16, unique=True, verbose_name=u'项目代号')
    linkman = models.CharField(max_length=16, blank=True, null=True, default='', verbose_name=u'项目负责人')
    phone = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'负责人电话')
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name
    

NATION_TYPE = (
    ("China", "China"),
    ("Foreign", "Foreign")
    )

class Areas(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'区域名称')
    areamark = models.CharField(max_length=16, unique=True, verbose_name=u'区域代号')
    nation_type = models.CharField(choices=NATION_TYPE, max_length=32, default="China", verbose_name=u"区域类型")
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name
    

class Functions(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'功能名称')
    functionmark = models.CharField(max_length=16, unique=True, verbose_name=u'功能代号')
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name


class ServerType(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=u'系统名称')
    vers = models.CharField(max_length=32, verbose_name=u'系统版本')
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")

    def __unicode__(self):
        return self.name
    

class ApplyVocational(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=u'应用名称')
    applymark = models.CharField(max_length=32, verbose_name=u'应用代号')
    date_added = models.DateTimeField(auto_now=True)    
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name


APPLY_TYPE_DIR = {1:'sys', 2:'app'}

def get_upload_to(instance, fielname):
    apptype = instance.apply_type
    if apptype:
        typedir = APPLY_TYPE_DIR[apptype]
    else:
        typedir = 'upload'
    return '/'.join([typedir, instance.servername.name, fielname])

APPLY_TYPE = (
    (1, "系统服务"),
    (2, "程序服务") 
    )
class ApplyFile(models.Model):
    name = models.CharField(max_length=64, verbose_name=u'应用文件名称')
    appfile = models.FileField(upload_to=get_upload_to, verbose_name=u'应用文件')
    apply_type = models.IntegerField(choices=APPLY_TYPE, blank=True, verbose_name=u"应用服务类型")
    date_added = models.DateTimeField(auto_now=True)    
    appvers = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"版本号")
    servername = models.ForeignKey("ApplyVocational", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'应用名称')
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name
    

TOOLS_TYPE = (
    (1, "ansible"),
    (2, "saltstack"),
    (3, "jenkins")    
    )
class ConfigVocational(models.Model):
    name = models.CharField(max_length=128, verbose_name=u'业务配置名称')
    configmark = models.CharField(max_length=64, verbose_name=u'业务配置代号')
    servername = models.ForeignKey("ApplyVocational", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'应用名称')    
    configfile = models.ManyToManyField("ApplyFile", blank=True, null=True, verbose_name=u"应用文件")
    tools_type = models.IntegerField(choices=TOOLS_TYPE, blank=True, default=1, verbose_name=u"工具格式类型")
    idc = models.ForeignKey("IDC", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'机房')
    item = models.ForeignKey("Items", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'项目')
    area = models.ForeignKey("Areas", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'区域')
    functs = models.ForeignKey("Functions", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'功能')    
    ostype = models.ForeignKey("ServerType", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'操作系统')    
    date_added = models.DateTimeField(auto_now=True)    
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name
    

class VersionVocational(models.Model):
    versionpath = models.CharField(max_length=255, verbose_name=u'版本配置路径')
    name = models.CharField(max_length=32, verbose_name=u'版本名称')
    versionmark = models.CharField(max_length=16, verbose_name=u'版本号')
    idc = models.ForeignKey("IDC", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'机房')
    item = models.ForeignKey("Items", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'项目')
    area = models.ForeignKey("Areas", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'区域')
    functs = models.ForeignKey("Functions", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'功能')    
    date_added = models.DateTimeField(auto_now=True)    
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name


class TaskName(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"配置任务名称")
    confstep = models.PositiveSmallIntegerField(blank=True, null=True, default=1, verbose_name=u"步骤计数")
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name    


CONF_STEP = (
    (1, "第一步"),
    (2, "第二步"),
    (3, "第三步"),   
    (4, "第四步"),   
    (5, "第五步"),   
    (6, "第六步"),   
    (7, "第七步"),   
    (8, "第八步"),   
    (9, "第九步"),   
    (10, "第十步")   
    )    
class ConfigPlanTask(models.Model):
    name = models.ForeignKey("TaskName", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u"配置任务名称")
    servername = models.ForeignKey("ApplyVocational", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'应用名称')
    confname = models.ForeignKey("ConfigVocational", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'业务配置')
    confstep = models.IntegerField(choices=CONF_STEP, blank=True, default=1, verbose_name=u"步骤计数")
    date_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name.name   


class PlanVocational(models.Model):
    name = models.CharField(max_length=64, verbose_name=u'方案名称')
    planmark = models.CharField(max_length=32, unique=True, verbose_name=u'方案代号')
    idc = models.ForeignKey("IDC", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'机房')
    item = models.ForeignKey("Items", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'项目')
    area = models.ForeignKey("Areas", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'区域')
    functs = models.ForeignKey("Functions", blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'功能')
    configset = models.ManyToManyField("ConfigPlanTask", blank=True, null=True, verbose_name=u'配置任务')    
    date_added = models.DateTimeField(auto_now=True)    
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    
    def __unicode__(self):
        return self.name
    

ASSET_STATUS = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u"报废")
    )
class HostAsset(models.Model):
    wan_ip = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"外网IP")
    lan_ip = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"内网IP")
    other_ip = models.CharField(max_length=255, blank=True, null=True, verbose_name=u"其他IP")
    hostname = models.CharField(unique=True, max_length=128, verbose_name=u"主机名")
    username = models.CharField(max_length=16, blank=True, null=True, default='root', verbose_name=u"管理用户名")
    password = models.CharField(max_length=256, blank=True, null=True, verbose_name=u"密码")

jpydispose/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from jpyasset.models import HostAsset, PlanVocational


TASK_STATUS = (
    (1, u"未执行"),
    (2, u"已执行")
    )

class Tasklist(models.Model):
    taskid = models.BigIntegerField(verbose_name=u"任务ID")
    host = models.ManyToManyField(HostAsset, verbose_name=u"主机ID")
    plan = models.ManyToManyField(PlanVocational, blank=True, null=True, verbose_name=u'方案ID')
    status = models.IntegerField(choices=TASK_STATUS, blank=True, null=True, default=1, verbose_name=u"任务状态")
    update_time = models.DateTimeField(auto_now=True)
    create_time = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.taskid  


RATE_STATUS = (
    (1, u"执行成功"),
    (2, u"执行失败")
    )

class Taskrate(models.Model):
    task = models.ForeignKey("Tasklist", blank=True, null=True, on_delete=models.SET_NULL, verbose_name=u'任务ID')
    status = models.IntegerField(choices=RATE_STATUS, blank=True, null=True, default=1, verbose_name=u"执行状态")
    create_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.status
    

class Taskcmdhistory(models.Model):
    task = models.ForeignKey("Tasklist", blank=True, null=True, on_delete=models.SET_NULL, verbose_name=u'任务ID')
    fruits = models.TextField()
    create_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.fruits
    
    
class TaskTest(models.Model):
    hostip = models.CharField(max_length=128, blank=True, null=True)
    fruits = models.TextField()
    create_time = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.fruits    

templates/jpyasset/conf.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav_cat_bar.html' %}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
            <div class="panel blank-panel">
				<div class="panel-heading">
					<div class="panel-options">
	                    <ul class="nav nav-tabs" id="appchg">
	                        <li class="active"><a href="{% url 'confvl_list' %}"><i class="fa fa-cog"></i> 配置设置</a>
	                        </li>
	                        <li class=""><a href="{% url 'conftaskname_list' %}"><i class="fa fa-navicon"></i> 任务名称</a>
	                        </li>
	                        <li class=""><a href="{% url 'conftaskset_list' %}"><i class="fa  fa-tasks"></i> 任务设置</a>
	                        </li>
	                    </ul>
					</div>
				</div>            
				<div class="panel-body">
					<div class="tab-content">

						{% block contentapp %}{% endblock %}
												           
					</div>   
				</div>            
			</div>   
		</div>
    </div>
</div>
{% endblock %}
{% block self_footer_js %}
<script>

</script>
{% endblock %}

templates/jpyasset/filevl_edit.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap %}
{% include 'nav_cat_bar.html' %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5> 填写应用文件基本信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">未启用 1</a>
                            </li>
                            <li><a href="#">未启用 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    {% if emg %}
                        <div class="alert alert-warning text-center">{{ emg }}</div>
                    {% endif %}
                    {% if smg %}
                        <div class="alert alert-success text-center">{{ smg }}</div>
                    {% endif %}
                    <form id="filevlForm" method="post" class="form-horizontal" enctype="multipart/form-data" accept-charset="utf-8">
                        {{ filevl_form.servername|bootstrap_horizontal }}
                        
                        <div class="hr-line-dashed"></div>
                        {{ filevl_form.name|bootstrap_horizontal }}

                        <div class="hr-line-dashed"></div>
                        {{ filevl_form.appfile|bootstrap_horizontal }}
                        
                        <div class="hr-line-dashed"></div>
                        {{ filevl_form.apply_type|bootstrap_horizontal }}
                        
                        <div class="hr-line-dashed"></div>
                        {{ filevl_form.appvers|bootstrap_horizontal }}

                        <div class="hr-line-dashed"></div>
                        {{ filevl_form.comment|bootstrap_horizontal }}

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-5">
                                <button class="btn btn-white" type="submit"> 重置 </button>
                                <button class="btn btn-primary" type="sumbit"> 提交 </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var required_fields = ["id_name"];
    required_fields.forEach(function(field) {
        $('label[for="' + field + '"]').parent().addClass("required");
    });

    $('#filevlForm').validator({
        timely: 2,
        theme: "yellow_right_effect",
        fields: {
            "j_filevl": {
                rule: "required",
                tip: "输入应用文件名",
                ok: "",
                msg: {required: "应用文件名必须填写!"},
                data: {'data-ok':"应用文件名可以使用", 'data-msg-required': '应用文件名已正确'}
            }
        },
        valid: function(form) {
            form.submit();
        }
    });
    

	$('document').ready(function(){
		$('#id_appfile').mouseout(function(){
			var filedir = $(this).val().split('\\')
			var filename = filedir[filedir.length -1]
			if (filename != ''){
				document.getElementById("id_name").value=filename
			}
		});
	});
	
	  
    
</script>

{% endblock %}

templates/jpyasset/jhost_list_cu.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}
{% include 'nav_cat_bar.html' %}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> 主机信息列表</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="">
                    <form id="search_form" method="get" action="" class="pull-right mail-search">
                        <div class="input-group">
                            <input type="text" class="form-control input-sm" id="search_input" name="keyword" placeholder="Search">
                            <input type="text" style="display: none">
                            <div class="input-group-btn">
                                <button id='search_btn' type="submit" class="btn btn-sm btn-primary">
                                    Search
                                </button>
                            </div>
                        </div>
                    </form>
                    </div>

                    <form id="contents_form" name="contents_form">
                    <table class="table table-striped table-bordered table-hover " id="editable" >
                        <thead>
                            <tr>
                                {% ifequal 2 2 %}
                                    <th class="text-center"><input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('contents_form')"></th>
                                {% endifequal %}
                                <th class="text-center"> 主机名 </th>
                                <th class="text-center"> 外网IP地址 </th>
                                <th class="text-center"> 内网IP地址 </th>
                                <th class="text-center"> IDC </th>
                                <th class="text-center"> 所属项目组 </th>
                                <th class="text-center"> 所属区域组 </th>
                                <th class="text-center"> 所属功能组 </th>
                                <th class="text-center"> 操作系统 </th>
                                <th class="text-center"> CPU核数 </th>
                                <th class="text-center"> 内存 </th>
                                <th class="text-center"> 硬盘 </th>
                                <th class="text-center"> 使用状态 </th>
                                <th class="text-center"> 备注 </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for host in contacts.object_list  %}
                            <tr class="gradeX">
                                <td class="text-center" name="j_id" value="{{ host.id }}" data-editable='false'><input name="id" value="{{ host.id }}" type="checkbox" class="i-checks"></td>
                                <td class="text-center"> {{ host.hostname|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.wan_ip|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.lan_ip|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.idc.name|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.item.name|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.area.name|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.functs.name|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.system_type|default_if_none:"" }} {{ host.system_version|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.cpu|get_cpu_core|default_if_none:"" }}{% if host.cpu %}核{% endif %}</td>
                                <td class="text-center"> {{ host.memory|default_if_none:"" }}{% if host.memory %}G{% endif %}</td>
                                <td class="text-center"> {{ host.disk|default_if_none:"" }}{% if host.disk %}G{% endif %}</td>
                                <td class="text-center"> {{ host.get_status_display|default_if_none:"" }} </td>
                                <td class="text-center"> {{ host.comment|default_if_none:"" }} </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                   <div class="row">
                        <div class="col-sm-6">
                            <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                                Showing {{ contacts.start_index }} to {{ contacts.end_index }} of {{ p.count }} entries
                            </div>
                        </div>
                        {% include 'paginator.html' %}
                    </div>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block self_footer_js %}
<script>

</script>
{% endblock %}